### ISSUE TITLE
Include files path is relative and extra slash

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-cloud-openshift#30]
The include file path `../guides-common//gitclone.adoc` in the second section of the guide should be an absolute file path as it is in the `guide-rest-intro` repo. Also, the second slash before `gitclone.doc` should be a single slash.

YK has raised a general issue to check/fix this but could this one be fixed (and any other include references in this guide) so that we can continue testing it getting the same source built by the RH build system? Thx

**Comment by yeekangc** [comment]
@MaiHameed, please address as soon as possible.

**Comment by gkwan-ibm** [comment]
We use `../guides-common` instead of http url because the site/UI can pick up the common docs from the same branch of the guides, ie. master, qa, dev

**Comment by yeekangc** [comment]
Relative paths will cause issues and did hence a direct path to the common content was used.  We need to look into this and update what's needed.
