### ISSUE TITLE
Create a guide for OKD

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-cloud-openshift#32]
add a section to describe OKD

**Comment by yeekangc** [comment]
It may make more sense to have a separate guide for OKD.  I am interested in what the team has in mind here.

**Comment by evelinec** [comment]
- created the repo for the new guide
- working on the draft, can demo on next demo date

**Comment by MaiHameed** [comment]
In progress, repo can be found here: https://github.com/OpenLiberty/draft-guide-okd

**Comment by evelinec** [comment]
- try to run Linux tests on a physical machine

**Comment by evelinec** [comment]
- finished guide on all platform, pending on dev content review
- working travis test script

**Comment by evelinec** [comment]
- updated travis test for basic tests (same as other cloud guides)
- working on the tests using OpenShift cluster

**Comment by gkwan-ibm** [comment]
dup of https://github.com/openliberty/guides-common/issues/358
