### ISSUE TITLE
Update OpenShift guide to use the OL Operator

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-cloud-openshift#44]
Although using the OL Operator was considered when the OpenShift guide was written, the Operator wasn't ready for the big time. Now it is, can we update the OpenShift guide? @yeekangc

**Comment by yeekangc** [comment]
@gkwan-ibm @MaiHameed ^^^

**Comment by gkwan-ibm** [comment]
dup of https://github.com/OpenLiberty/guides-common/issues/411

close this one because 411 has more comments
