### ISSUE TITLE
Dockerfile changes required

### ISSUE THREAD

**Issue by aadeshpa** [OpenLiberty/guide-cloud-openshift#51]
COPY --chown=1001:0 target/system.war /config/apps

The above line does not work, when i moved it to below line it worked for me.

COPY target/system.war /config/dropins/

1. The `/config/apps` was wrong location to put the war file.
2. The command `chown` gave me error

```
Step 3/7 : ARG REVISION=SNAPSHOT
 ---> Using cache
 ---> a8068d720130
Step 4/7 : LABEL org.opencontainers.image.authors "Mai Hameed" org.opencontainers.image.vendor "Open Liberty" org.opencontainers.image.url "local" org.opencontainers.image.source "https://github.com/OpenLiberty/guide-cloud-openshift" org.opencontainers.image.version "$VERSION" org.opencontainers.image.revision "$REVISION" vendor "Open Liberty" name "system" version "$VERSION-$REVISION" summary "The system microservice from the Deploying microservices to OpenShift guide" description "This image contains the system microservice running with the Open Liberty runtime."
 ---> Using cache
 ---> aa6e0f1d93ee
Step 5/7 : COPY --chown=1001:0 src/main/liberty/config /config/
Unknown flag: chown
```

**Comment by MaiHameed** [comment]
Thanks for bringing this up @aadeshpa, I'll look into this and make changes accordingly.

**Comment by MaiHameed** [comment]
The Dockerfile is configured correctly following the best practices put out by the OL Docker team, you can check out their docs [here](https://github.com/OpenLiberty/ci.docker). The issue with the `chown` flag is known. The flag was introduced in Docker v17.09, so it seems like your Docker version is outdated. Updating Docker will fix the issue.

**Comment by MaiHameed** [comment]
Closing
