### ISSUE TITLE
I could reach to the system application till `http://system-route-deployment-learning.apps.eaglets.os.fyre.ibm.com/system/`

### ISSUE THREAD

**Issue by aadeshpa** [OpenLiberty/guide-cloud-openshift#52]
<img width="1352" alt="Screen Shot 2020-03-15 at 9 01 28 AM" src="https://user-images.githubusercontent.com/53223993/76701815-0189e600-669b-11ea-9acf-f28034ed442e.png">

I could not reach to /system/properties

<img width="1293" alt="Screen Shot 2020-03-15 at 9 02 11 AM" src="https://user-images.githubusercontent.com/53223993/76701830-1ebeb480-669b-11ea-8b4d-1acc12dc8216.png">

**Comment by MaiHameed** [comment]
Hello @aadeshpa could I get more details on the environment you're running? Is this a local OCP deployment on your personal Fyre VM?

**Comment by aadeshpa** [comment]
I used OCP 4.3 cluster of  3 master 3 nodes on top of base os as RHEL 7.6 OS

**Comment by MaiHameed** [comment]
I see. The guide is specifically tailored towards deploying applications to OpenShift Online, which is different from OpenShift Container Platform. I understand that conceptually it should be the same, however my assumption is that the minor environmental differences may have been the reason behind the bugs/issues. 

However, I'll try deploying the same environment to see if I can reproduce the issue, and will let you know the results.

**Comment by MaiHameed** [comment]
Hey @aadeshpa, could I get details on how you deployed the application? Did you follow the exact steps of the guide? If so, how did you access the internal registry? I know that the behaviour and set up of that particular portion is a little different.

**Comment by MaiHameed** [comment]
Hello @aadeshpa, could you please let me know if you're having issues? Otherwise I'll be closing this and #51 due to inactivity. Thanks :)

**Comment by aadeshpa** [comment]
Please go ahead and close for now, i did the workaround to get it working. This was just for my learning. ThanksAshish DeshpandeSoftware Developer, IBM WebSphere in the cloud DevelopmentCertified Scrum Master (http://bcert.me/smftnelom)email id: aadeshpa@us.ibm.comIBM Poughkeepsie, NYBuilding: 707   Floor: 1    Office: J09, Cell Phone: (312)4682490-----Mai Hameed <notifications@github.com> wrote: -----To: OpenLiberty/guide-cloud-openshift <guide-cloud-openshift@noreply.github.com>From: Mai Hameed <notifications@github.com>Date: 03/26/2020 11:15AMCc: Ashish Deshpande <aadeshpa@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [OpenLiberty/guide-cloud-openshift] I could reach to the system application till `http://system-route-deployment-learning.apps.eaglets.os.fyre.ibm.com/system/` (#52)Hello @aadeshpa, could you please let me know if you're having issues? Otherwise I'll be closing this and #51 due to inactivity. Thanks :)

**Comment by MaiHameed** [comment]
Glad you find a solution! Please reach out if you have any other issues.
