### ISSUE TITLE
OpenShift version update

### ISSUE THREAD

**Issue by bbaassssiiee** [OpenLiberty/guide-cloud-openshift#65]
The guide uses OpenShift 3, version 4 has been around for a while. Please update.

**Comment by AustinSeto** [comment]
Docker Daemon is not supported in OpenShift 4, may require reworking the guide as it uses Docker, will look into reworking guide

**Comment by AustinSeto** [comment]
Openshift Operator guide will be used for for OpenShift 4.x and this guide will remain for OpenShift 3.x with an update that will make note of the Openshift Operator guide.

**Comment by bbaassssiiee** [comment]
For OpenShift 4.x refer to https://github.com/OpenLiberty/draft-guide-cloud-openshift-operator
